version: '3.7'
services:
  nginx:
    image: ${NAME}_nginx:${VERSION}
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - default
      - kw_default
    deploy:
      labels:
        traefik.docker.network: kw_default
        traefik.frontend.rule: Host:techradar.local
        traefik.port: 8000
networks:
  kw_default:
    external: true